<?php

namespace AppBundle\Repository;

/**
 * userTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class userTokenRepository extends \Doctrine\ORM\EntityRepository
{

    public function getDateMax($date, $mail)
    {
        $result = $this->createQueryBuilder('userToken')
            //->select('userToken.expirationDate')
            //->where('NOW() < :paramDate')
            ->andWhere('userToken.userEmail = :paramMail')

            ->setParameters([
              //  'paramDate' => $date,
                'paramMail' => $mail
            ])
            ->getQuery()
            ->getOneOrNullResult();
        return $result;
    }
   public function check($email, $token)
    {
        $result = $this->createQueryBuilder('userToken')
            //->select('userToken.userEmail')
            ->andWhere('userToken.userEmail = :paramMail')
            ->andWhere('userToken.token = :paramToken')
            ->andWhere('userToken.expirationDate > NOW()')

            ->setParameters([
                'paramMail' => $email,
                'paramToken' => $token

            ])
            ->getQuery()
            ->getOneOrNullResult();
        return $result;
    }
}
