imports:
    - { resource: config.yml }

framework:
    router:
        resource: '%kernel.project_dir%/app/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ['!event']
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
        # To follow logs in real time, execute the following command:
        # `bin/console server:log -vv`
        server_log:
            type: server_log
            process_psr_3_messages: false
            host: 127.0.0.1:9911
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
swiftmailer:
    spool:     { type: memory }
    transport: smtp
    host:      smtp.mailtrap.io
    username:  15dfa59e0d38b2
    password:  40e65806871c19
    auth_mode: cram-md5
    port: 2525

#swiftmailer:
    delivery_addresses: ['19a80d9ecd-b91494@inbox.mailtrap.io']
parameters:
    database_name: commerce
    database_user: root
    database_password: troiswa